version: '3.4'

services:
    laravel-api:
        build: .
        hostname: api-datainfo
        container_name: api-datainfo
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html
        networks:
            - app-network
        depends_on:
            - mysql-app

    mysql-app:
        hostname: mysql
        container_name: mysql
        image: mysql:5.7.22
        command: --innodb-use-native-aio=0
        ports:
            - "3306:3306"
        volumes:
            - .docker/dbdata:/var/lib/mysql
        environment:
            MYSQL_DATABASE: todo_list
            MYSQL_ROOT_PASSWORD: root
        networks:
            - app-network

    adminer:
        depends_on:
            - mysql-app
        container_name: myadmin
        image: adminer
        restart: always
        ports:
            - 8888:8080
        networks:
            - app-network
networks:
    app-network:
